/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package batalhanaval;

/**
 *
 * @author User
 */
public class Tela extends javax.swing.JFrame {

  /**
   * Creates new form Tela
   */
  public Tela() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    jButton6 = new javax.swing.JButton();
    jButton7 = new javax.swing.JButton();
    jButton8 = new javax.swing.JButton();
    jButton9 = new javax.swing.JButton();
    jButton10 = new javax.swing.JButton();
    jButton11 = new javax.swing.JButton();
    jButton12 = new javax.swing.JButton();
    jButton13 = new javax.swing.JButton();
    jButton14 = new javax.swing.JButton();
    jButton15 = new javax.swing.JButton();
    jButton16 = new javax.swing.JButton();
    jButton17 = new javax.swing.JButton();
    jButton18 = new javax.swing.JButton();
    jButton19 = new javax.swing.JButton();
    jButton20 = new javax.swing.JButton();
    jButton21 = new javax.swing.JButton();
    jButton22 = new javax.swing.JButton();
    jButton23 = new javax.swing.JButton();
    jButton24 = new javax.swing.JButton();
    jButton25 = new javax.swing.JButton();
    jButton26 = new javax.swing.JButton();
    jButton27 = new javax.swing.JButton();
    jButton28 = new javax.swing.JButton();
    jButton29 = new javax.swing.JButton();
    jButton30 = new javax.swing.JButton();
    jButton31 = new javax.swing.JButton();
    jButton32 = new javax.swing.JButton();
    jButton33 = new javax.swing.JButton();
    jButton34 = new javax.swing.JButton();
    jButton35 = new javax.swing.JButton();
    jButton36 = new javax.swing.JButton();
    jButton37 = new javax.swing.JButton();
    jButton38 = new javax.swing.JButton();
    jButton39 = new javax.swing.JButton();
    jButton40 = new javax.swing.JButton();
    jButton41 = new javax.swing.JButton();
    jButton42 = new javax.swing.JButton();
    jButton43 = new javax.swing.JButton();
    jButton44 = new javax.swing.JButton();
    jButton45 = new javax.swing.JButton();
    jButton46 = new javax.swing.JButton();
    jButton47 = new javax.swing.JButton();
    jButton48 = new javax.swing.JButton();
    jButton49 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Batalha Naval");
    getContentPane().setLayout(new java.awt.GridLayout(7, 7));

    jButton1.setText("jButton1");
    getContentPane().add(jButton1);

    jButton2.setText("jButton1");
    getContentPane().add(jButton2);

    jButton3.setText("jButton1");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton3);

    jButton4.setText("jButton1");
    getContentPane().add(jButton4);

    jButton5.setText("jButton1");
    getContentPane().add(jButton5);

    jButton6.setText("jButton1");
    getContentPane().add(jButton6);

    jButton7.setText("jButton1");
    getContentPane().add(jButton7);

    jButton8.setText("jButton1");
    getContentPane().add(jButton8);

    jButton9.setText("jButton1");
    getContentPane().add(jButton9);

    jButton10.setText("jButton1");
    getContentPane().add(jButton10);

    jButton11.setText("jButton1");
    getContentPane().add(jButton11);

    jButton12.setText("jButton1");
    getContentPane().add(jButton12);

    jButton13.setText("jButton1");
    getContentPane().add(jButton13);

    jButton14.setText("jButton1");
    getContentPane().add(jButton14);

    jButton15.setText("jButton1");
    getContentPane().add(jButton15);

    jButton16.setText("jButton1");
    getContentPane().add(jButton16);

    jButton17.setText("jButton1");
    getContentPane().add(jButton17);

    jButton18.setText("jButton1");
    getContentPane().add(jButton18);

    jButton19.setText("jButton1");
    getContentPane().add(jButton19);

    jButton20.setText("jButton1");
    getContentPane().add(jButton20);

    jButton21.setText("jButton1");
    getContentPane().add(jButton21);

    jButton22.setText("jButton1");
    getContentPane().add(jButton22);

    jButton23.setText("jButton1");
    getContentPane().add(jButton23);

    jButton24.setText("jButton1");
    getContentPane().add(jButton24);

    jButton25.setText("jButton1");
    getContentPane().add(jButton25);

    jButton26.setText("jButton1");
    getContentPane().add(jButton26);

    jButton27.setText("jButton1");
    getContentPane().add(jButton27);

    jButton28.setText("jButton1");
    getContentPane().add(jButton28);

    jButton29.setText("jButton1");
    getContentPane().add(jButton29);

    jButton30.setText("jButton1");
    getContentPane().add(jButton30);

    jButton31.setText("jButton1");
    getContentPane().add(jButton31);

    jButton32.setText("jButton1");
    getContentPane().add(jButton32);

    jButton33.setText("jButton1");
    getContentPane().add(jButton33);

    jButton34.setText("jButton1");
    getContentPane().add(jButton34);

    jButton35.setText("jButton1");
    getContentPane().add(jButton35);

    jButton36.setText("jButton1");
    getContentPane().add(jButton36);

    jButton37.setText("jButton1");
    getContentPane().add(jButton37);

    jButton38.setText("jButton1");
    getContentPane().add(jButton38);

    jButton39.setText("jButton1");
    getContentPane().add(jButton39);

    jButton40.setText("jButton1");
    getContentPane().add(jButton40);

    jButton41.setText("jButton1");
    getContentPane().add(jButton41);

    jButton42.setText("jButton1");
    getContentPane().add(jButton42);

    jButton43.setText("jButton1");
    getContentPane().add(jButton43);

    jButton44.setText("jButton1");
    getContentPane().add(jButton44);

    jButton45.setText("jButton1");
    getContentPane().add(jButton45);

    jButton46.setText("jButton1");
    getContentPane().add(jButton46);

    jButton47.setText("jButton1");
    getContentPane().add(jButton47);

    jButton48.setText("jButton1");
    getContentPane().add(jButton48);

    jButton49.setText("jButton1");
    getContentPane().add(jButton49);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButton3ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Tela().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton10;
  private javax.swing.JButton jButton11;
  private javax.swing.JButton jButton12;
  private javax.swing.JButton jButton13;
  private javax.swing.JButton jButton14;
  private javax.swing.JButton jButton15;
  private javax.swing.JButton jButton16;
  private javax.swing.JButton jButton17;
  private javax.swing.JButton jButton18;
  private javax.swing.JButton jButton19;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton20;
  private javax.swing.JButton jButton21;
  private javax.swing.JButton jButton22;
  private javax.swing.JButton jButton23;
  private javax.swing.JButton jButton24;
  private javax.swing.JButton jButton25;
  private javax.swing.JButton jButton26;
  private javax.swing.JButton jButton27;
  private javax.swing.JButton jButton28;
  private javax.swing.JButton jButton29;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton30;
  private javax.swing.JButton jButton31;
  private javax.swing.JButton jButton32;
  private javax.swing.JButton jButton33;
  private javax.swing.JButton jButton34;
  private javax.swing.JButton jButton35;
  private javax.swing.JButton jButton36;
  private javax.swing.JButton jButton37;
  private javax.swing.JButton jButton38;
  private javax.swing.JButton jButton39;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton40;
  private javax.swing.JButton jButton41;
  private javax.swing.JButton jButton42;
  private javax.swing.JButton jButton43;
  private javax.swing.JButton jButton44;
  private javax.swing.JButton jButton45;
  private javax.swing.JButton jButton46;
  private javax.swing.JButton jButton47;
  private javax.swing.JButton jButton48;
  private javax.swing.JButton jButton49;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton jButton6;
  private javax.swing.JButton jButton7;
  private javax.swing.JButton jButton8;
  private javax.swing.JButton jButton9;
  // End of variables declaration//GEN-END:variables
}
